name: Mac OS

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/build_and_test.yml'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/build_and_test.yml'
  workflow_dispatch:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/build_and_test.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: brew install postgresql
      - run: echo "POSTGRESQL_CONFIG=$(sudo -u postgres psql -t -c 'SHOW config_file')" >> $GITHUB_ENV
      - run: brew install boost
      - uses: actions/checkout@v4
      - run: make && make tdkc && make install
      - run: echo "shared_preload_libraries = 'provsql'" >> $GITHUB_ENV
      - run: brew services restart postgresql
      - run: make installcheck
